(()=>{
'use strict';
const API='https://script.google.com/macros/s/AKfycby4tO2Y1xWbVv1XqzbIYjuTKOt4XRWPzB9MseMC1x-qc8gbNYPvqvG1z6PuCPGZi5O2/exec';
const $=id=>document.getElementById(id);
const S={token:sessionStorage.getItem('nel_b2b_token')||'',data:null,cart:{},installPrompt:null,legal:null,seq:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const num=v=>Number(v||0);
const digits=v=>String(v||'').replace(/\D/g,'').slice(-10);
function toast(msg){const t=$('toast');t.textContent=msg||'';t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function busy(on,text='Loading…'){$('globalBusy').classList.toggle('show',!!on);$('globalBusyText').textContent=text}
function jsonp(method,args=[]){return new Promise((resolve,reject)=>{const cb='__nelB2B'+Date.now()+(++S.seq)+Math.floor(Math.random()*10000),sc=document.createElement('script');let done=false;const clean=()=>{if(done)return;done=true;clearTimeout(timer);try{delete window[cb]}catch(e){window[cb]=undefined}sc.remove()};window[cb]=p=>{clean();p=p||{};p.ok?resolve(p.result):reject(new Error(p.error||'Request failed.'))};sc.onerror=()=>{clean();reject(new Error('Unable to connect. Please check internet and retry.'))};const payload={method:String(method||''),args:Array.isArray(args)?args:[],requestId:'b2b-'+Date.now()+'-'+S.seq};sc.async=true;sc.src=API+'?jsonp=1&callback='+encodeURIComponent(cb)+'&payload='+encodeURIComponent(JSON.stringify(payload))+'&v=1300&_='+Date.now();document.head.appendChild(sc);const timer=setTimeout(()=>{clean();reject(new Error('Connection timed out. Please retry.'))},15000)})}
function cacheData(d){try{sessionStorage.setItem('nel_b2b_data_v130',JSON.stringify(d))}catch(e){}}
function getCached(){try{return JSON.parse(sessionStorage.getItem('nel_b2b_data_v130')||'null')}catch(e){return null}}
function clearSession(){sessionStorage.removeItem('nel_b2b_token');sessionStorage.removeItem('nel_b2b_data_v130');S.token='';S.data=null;S.cart={}}
function setLogged(logged){$('loginView').classList.toggle('hidden',logged);$('appView').classList.toggle('hidden',!logged);$('bottomNav').classList.toggle('hidden',!logged);$('menuBtn').classList.toggle('hidden',!logged);if(logged)showView('home')}
function syncStatus(text,ok=false){const x=$('syncStatus');x.textContent=text||'';x.classList.toggle('ok',!!ok)}
async function login(){const mobile=digits($('mobile').value),pin=$('pin').value.trim();$('loginMsg').textContent='';if(!/^[6-9]\d{9}$/.test(mobile)||pin.length<4){$('loginMsg').textContent='Enter a valid mobile number and PIN.';return}const b=$('loginBtn');b.disabled=true;b.textContent='Signing in…';try{const r=await jsonp('vendorLogin',[mobile,pin]);if(!r||!r.token)throw new Error('Login failed.');S.token=r.token;sessionStorage.setItem('nel_b2b_token',S.token);setLogged(true);syncStatus('Loading latest…');await refresh(true);toast('Welcome to Native Elaneeru Business')}catch(e){$('loginMsg').textContent=e.message;toast(e.message)}finally{b.disabled=false;b.textContent='Login'}}
async function refresh(showLoader=false){if(!S.token)return;if(showLoader&&!S.data)busy(true,'Loading your business catalogue…');try{const d=await jsonp('getB2BAppDataV9',[S.token]);S.data=d||{};cacheData(S.data);render();syncStatus('Updated now',true)}catch(e){if(/expired|inactive|invalid token/i.test(e.message)){logout(false);toast('Session expired. Please login again.')}else{syncStatus('Could not refresh');toast(e.message)}}finally{busy(false)}}
function uniqueBanners(arr){const seen=new Set();return (arr||[]).filter(b=>{const k=[b.title,b.subtitle,b.offerText].map(x=>String(x||'').trim().toLowerCase()).join('|');if(seen.has(k))return false;seen.add(k);return true}).slice(0,5)}
function render(){const d=S.data||{},v=d.vendor||{};$('headerLocation').textContent=v.area?'📍 '+v.area:'Business ordering';$('businessName').textContent=v.businessName||'Business Account';$('businessMeta').textContent=[v.ownerName,v.area].filter(Boolean).join(' · ');$('businessArea').textContent=v.area||'—';renderBanners(uniqueBanners(d.banners));renderTarget(d.target);renderMarket(d.marketRates);$('products').innerHTML=(d.products||[]).map(productCard).join('')||emptyCard('No live B2B products right now.');$('orders').innerHTML=(d.orders||[]).map(orderCard).join('')||emptyCard('No orders yet.');$('account').innerHTML=accountHtml(v);renderCart()}
function renderBanners(bs){const h=$('bannerRail');if(!bs.length){h.innerHTML='<article class="banner"><div><span class="eyebrow">NATIVE ELANEERU BUSINESS</span><h2>Fresh wholesale supply</h2><p>Reliable tender coconut ordering for your business.</p></div><div class="bannerMark">🥥</div></article>';return}h.innerHTML=bs.map(b=>'<article class="banner">'+(b.imageUrl?'<img src="'+esc(b.imageUrl)+'" alt="">':'<div class="bannerMark">🥥</div>')+'<div><span class="eyebrow">WHOLESALE OFFER</span><h2>'+esc(b.title||'Native Elaneeru Business')+'</h2><p>'+esc(b.subtitle||'')+'</p>'+(b.offerText?'<strong>'+esc(b.offerText)+'</strong>':'')+'</div></article>').join('')}
function renderTarget(t){const h=$('targetHost');if(!t){h.innerHTML='';return}const target=Math.max(0,num(t.targetQty)),achieved=Math.max(0,num(t.achievedQty)),pct=target?Math.min(100,Math.round(achieved*100/target)):0;const complete=target>0&&achieved>=target;h.innerHTML='<div class="targetCard"><div class="targetTop"><div><span class="eyebrow">GROWTH TARGET</span><h3>'+esc(t.name||'Business Target')+'</h3></div><b>'+pct+'%</b></div><div class="progress"><span style="width:'+pct+'%"></span></div><p>'+(complete?'Target completed · '+target.toLocaleString('en-IN')+' pcs achieved':achieved.toLocaleString('en-IN')+' / '+target.toLocaleString('en-IN')+' pcs')+'</p>'+(t.rewardText?'<small>'+esc(t.rewardText)+'</small>':'')+'</div>'}
function latestMarket(rates){return Array.isArray(rates)&&rates.length?rates[0]:null}
function marketValue(r){return num(r&&(r.modalRate||r.maxRate||r.minRate))}
function comparable(rateUnit,unit){const r=String(rateUnit||'').toLowerCase().replace(/\s+/g,''),u=String(unit||'').toLowerCase().replace(/\s+/g,'');if(!r||!u||/(kg|quintal|ton|dozen|100|50|25)/.test(r))return false;return /(pc|pcs|piece|pieces|no|nos|each)/.test(r)&&/(pc|pcs|piece|pieces|no|nos|each)/.test(u)}
function renderMarket(rates){const r=latestMarket(rates),h=$('marketHost');if(!r||!marketValue(r)){h.innerHTML='<div class="marketSlim"><div><span class="eyebrow">MARKET PRICE</span><b>Latest tender coconut benchmark</b></div><small>Market update pending</small></div>';return}h.innerHTML='<div class="marketSlim"><div><span class="eyebrow">LATEST MARKET PRICE</span><b>'+esc(r.market||'Tender Coconut Market')+'</b><small>'+esc([r.district,r.state,r.source,r.rateDate].filter(Boolean).join(' · '))+'</small></div><strong>'+money(marketValue(r))+' <small>'+esc(r.rateUnit||'')+'</small></strong></div>'}
function productCard(p){const standard=num(p.standardPrice||p.defaultPrice||p.price),your=num(p.price),save=Math.max(0,num(p.savingsPerUnit||standard-your)),pct=num(p.savingsPercent||0),q=S.cart[p.productId]?.qty||num(p.moq||1),r=latestMarket(S.data?.marketRates),mv=marketValue(r);let market='';if(r&&mv){market=comparable(r.rateUnit,p.unit)?'<div class="priceRow marketRow"><span>Market Price</span><b>'+money(mv)+' / '+esc(p.unit||'pc')+'</b></div>':'<div class="benchmark">Market benchmark: '+money(mv)+' '+esc(r.rateUnit||'')+'</div>'}const img=p.imageUrl?'<img loading="lazy" src="'+esc(p.imageUrl)+'" alt="'+esc(p.productName)+'" onerror="this.outerHTML=\'🥥\'">':'🥥';return '<article class="productCard"><div class="productVisual">'+img+'</div><div class="productBody"><h3>'+esc(p.productName)+'</h3>'+market+'<div class="priceRow"><span>Standard Price</span><s>'+money(standard)+' / '+esc(p.unit||'pc')+'</s></div><div class="yourPrice"><span>Your Price</span><b>'+money(your)+' <small>/ '+esc(p.unit||'pc')+'</small></b></div>'+(save>0?'<div class="savePill">You save '+money(save)+' / '+esc(p.unit||'pc')+(pct?' · '+pct+'%':'')+'</div>':'')+'<p class="rules">MOQ '+num(p.moq||1)+' · order in steps of '+num(p.qtyStep||1)+'</p><div class="qtyRow"><button class="step" onclick="NEL.stepQty(\''+safeId(p.productId)+'\',-1)">−</button><input id="qty_'+esc(p.productId)+'" type="number" inputmode="numeric" value="'+q+'" min="'+num(p.moq||1)+'" step="'+num(p.qtyStep||1)+'"><button class="step" onclick="NEL.stepQty(\''+safeId(p.productId)+'\',1)">+</button><button class="addBtn" onclick="NEL.add(\''+safeId(p.productId)+'\')">Add</button></div></div></article>'}
function safeId(v){return String(v||'').replace(/'/g,"\\'")}
function stepQty(id,dir){const p=(S.data?.products||[]).find(x=>String(x.productId)===String(id));if(!p)return;const el=$('qty_'+id),step=Math.max(1,num(p.qtyStep||1)),min=Math.max(1,num(p.moq||1)),current=Math.max(min,num(el.value||min));el.value=Math.max(min,current+(dir*step))}
function add(id){const p=(S.data?.products||[]).find(x=>String(x.productId)===String(id));if(!p)return;const q=Math.floor(num($('qty_'+id)?.value));if(q<num(p.moq||1))return toast('MOQ is '+p.moq);if(num(p.qtyStep||1)>1&&q%num(p.qtyStep||1)!==0)return toast('Quantity must be in steps of '+p.qtyStep);S.cart[id]={product:p,qty:q};renderCart();toast(p.productName+' added')}
function renderCart(){const xs=Object.values(S.cart),qty=xs.reduce((a,x)=>a+x.qty,0),total=xs.reduce((a,x)=>a+x.qty*num(x.product.price),0);$('cartBar').classList.toggle('show',xs.length>0);$('cartSummary').textContent=qty+' pcs';$('cartAmount').textContent=money(total);$('cartItems').innerHTML=xs.map(x=>'<div class="cartLine"><div><b>'+esc(x.product.productName)+'</b><small>'+x.qty+' × '+money(x.product.price)+'</small></div><div><b>'+money(x.qty*num(x.product.price))+'</b><button onclick="NEL.remove(\''+safeId(x.product.productId)+'\')">Remove</button></div></div>').join('');$('cartTotal').textContent=money(total)}
function remove(id){delete S.cart[id];renderCart()}
function openCart(){$('cartSheet').classList.add('show');renderCart()}
function closeCart(){$('cartSheet').classList.remove('show')}
async function placeOrder(){const items=Object.values(S.cart).map(x=>({productId:x.product.productId,quantity:x.qty}));if(!items.length)return toast('Cart is empty');const v=S.data?.vendor||{},btn=$('placeBtn');btn.disabled=true;btn.textContent='Placing order…';try{const r=await jsonp('placeB2BOrderV9',[S.token,{items,paymentType:'COD',deliverySlot:$('slot').value||'',deliveryAddress:v.address||v.area||'',area:v.area||'',deliveryCharge:0}]);S.cart={};closeCart();renderCart();await refresh(false);showView('orders');toast('Order placed · '+(r?.orderId||'Success'))}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent='Place Order'}}
function orderCard(o){return '<article class="orderCard"><div class="orderHead"><div><b>'+esc(o.orderId)+'</b><span>'+esc(o.status||'Order Received')+'</span></div><strong>'+money(o.amount)+'</strong></div><p>'+esc(o.orderedAt||'')+'</p><div class="orderItems">'+(o.items||[]).map(i=>'<span>'+esc(i.productName)+' × '+num(i.quantity)+'</span>').join('')+'</div><div class="orderActions"><button onclick="NEL.track(\''+safeId(o.orderId)+'\')">📍 Track</button><button onclick="NEL.invoice(\''+safeId(o.orderId)+'\')">🧾 Invoice</button></div></article>'}
async function track(id){try{const d=await jsonp('getVendorLiveTracking',[S.token,id]);if(!d||!d.active)return toast('Live tracking is not active yet.');toast((num(d.stopsBefore)||0)+' stops before you'+(d.updatedAt?' · '+d.updatedAt:''))}catch(e){toast(e.message)}}
async function invoice(id){try{busy(true,'Preparing invoice…');const d=await jsonp('getB2BInvoiceV91',[S.token,id]);const w=window.open('','_blank');if(!w)return toast('Allow pop-ups to open invoice');w.document.write(invoiceHtml(d));w.document.close()}catch(e){toast(e.message)}finally{busy(false)}}
function invoiceHtml(d){const l=d.legal||{},rows=(d.items||[]).map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(x.productName)+'</td><td>'+esc(x.hsn)+'</td><td>'+num(x.qty)+'</td><td>'+money(x.rate)+'</td><td>'+money(x.lineAmount)+'</td></tr>').join('');return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+esc(d.invoiceNo)+'</title><style>body{font-family:Arial,sans-serif;margin:28px;color:#18312c}.brand{font-size:24px;font-weight:900;color:#1e5a48}.muted{color:#697871;font-size:12px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:9px;border-bottom:1px solid #dfe8e3;font-size:12px;text-align:left}.right{text-align:right}.total{font-size:18px;font-weight:900}@media print{button{display:none}body{margin:12mm}}</style></head><body><div class="brand">Native Elaneeru</div><b>'+esc(l.legalName||'Sri Govindadri Ventures')+'</b><div class="muted">'+esc(l.businessAddress||'')+'</div><h2>'+esc(d.documentType||'Commercial Invoice / Receipt')+'</h2><div class="muted">Invoice '+esc(d.invoiceNo)+' · '+esc(d.invoiceDate)+'<br>Order '+esc(d.orderId)+'</div><p><b>'+esc(d.partyName)+'</b><br><span class="muted">'+esc(d.address)+' · '+esc(d.mobile)+'</span></p><table><tr><th>#</th><th>Product</th><th>HSN</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>'+rows+'</table><p class="right total">Total '+money(d.total)+'</p><div class="muted">Payment: Cash on Delivery<br>FSSAI: '+esc(l.fssaiNo||'Application Pending')+'<br>GST: '+esc(l.gstin||'Not registered')+'<br>Customer care: '+esc(l.supportPhone||'')+'</div><button onclick="print()" style="margin-top:18px">Print / Save PDF</button></body></html>'}
function accountHtml(v){return '<div class="accountCard"><div class="accountAvatar">🏪</div><h2>'+esc(v.businessName||'Business Account')+'</h2><p>'+esc(v.ownerName||'')+'</p><div class="accountRows"><div><span>Mobile</span><b>'+esc(v.mobile||'—')+'</b></div><div><span>Area</span><b>'+esc(v.area||'—')+'</b></div><div><span>Address</span><b>'+esc(v.address||'—')+'</b></div><div><span>Payment</span><b>Cash on Delivery</b></div></div><a class="supportLink" href="tel:7411807675">☎ Contact Support</a></div>'}
function emptyCard(text){return '<div class="emptyCard">'+esc(text)+'</div>'}
function showView(v){['home','orders','account'].forEach(x=>$(x+'View').classList.toggle('hidden',x!==v));document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('on',b.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});if(v==='orders'&&S.token)refresh(false)}
function openMenu(){$('menuSheet').classList.add('show')}
function closeMenu(){$('menuSheet').classList.remove('show')}
async function openLegal(){closeMenu();$('legalSheet').classList.add('show');if(S.legal){renderLegal();return}$('legalBody').innerHTML='<div class="legalLoading">Loading legal information…</div>';try{S.legal=await jsonp('getCompliancePublicV91',[]);renderLegal()}catch(e){$('legalBody').innerHTML='<div class="emptyCard">'+esc(e.message)+'</div>'}}
function renderLegal(){const l=S.legal||{};$('legalBody').innerHTML=[['Legal entity',(l.legalName||'Sri Govindadri Ventures')+(l.legalStructure?' · '+l.legalStructure:'')],['Business address',l.businessAddress||'Bengaluru, Karnataka'],['FSSAI',l.fssaiNo||'Application Pending'],['GST',l.gstin||'Not registered'],['Grievance Officer',l.grievanceOfficer||''],['Grievance email',l.grievanceEmail||''],['Customer care',l.supportPhone||'7411807675'],['Invoice type',l.invoiceDocumentType||'Commercial Invoice / Receipt']].map(x=>'<div class="legalRow"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('')}
async function installApp(){closeMenu();if(S.installPrompt){S.installPrompt.prompt();await S.installPrompt.userChoice;S.installPrompt=null}else toast('Use browser menu → Add to Home Screen')}
function logout(callBackend=true){closeMenu();if(callBackend&&S.token)jsonp('vendorLogout',[S.token]).catch(()=>{});clearSession();setLogged(false);$('pin').value='';$('headerLocation').textContent='Business ordering';toast('Logged out')}
function bind(){
 $('loginBtn').onclick=login;$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('mobile').addEventListener('input',e=>e.target.value=digits(e.target.value));$('menuBtn').onclick=openMenu;$('menuClose').onclick=closeMenu;$('menuLegal').onclick=openLegal;$('menuInstall').onclick=installApp;$('menuLogout').onclick=()=>logout(true);$('menuSheet').onclick=e=>{if(e.target===$('menuSheet'))closeMenu()};$('legalClose').onclick=()=>$('legalSheet').classList.remove('show');$('cartClose').onclick=closeCart;$('placeBtn').onclick=placeOrder;document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>showView(b.dataset.view));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.installPrompt=e});
}
async function boot(){bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(!S.token){setLogged(false);return}const cached=getCached();if(cached){S.data=cached;setLogged(true);render();syncStatus('Updating…')}else{setLogged(true);syncStatus('Loading…')}await refresh(!cached)}
window.NEL={add,remove,stepQty,openCart,closeCart,placeOrder,track,invoice,showView,refresh};
boot();
})();